### ISSUE TITLE
No such file or directory: synthetic_5d_j2_16_noiselevels6_wide_438x202x320x8.npz

### ISSUE THREAD

**Issue by 520jz** [NaamaPearl/nan#12]
Hello, when I run the train.py file according to your tutorial, the following error occurs. What is this synthetic_5d_j2_16_noiselevels6_wide_438x202x320x8.npz file? Why do I need this file? I am using the NeRF llff dataset, and I remember that there is no such file in the Nerf llff dataset.
![image](https://github.com/user-attachments/assets/dcda65cb-5395-4b74-b6d8-e51323871f7b)
![image](https://github.com/user-attachments/assets/59419522-029c-4f29-b6c2-170c6da8f8d7)

**Comment by NaamaPearl** [comment]
Hi,

This file is the test set in the paper "KPN: Burst Denoising with Kernel Prediction Networks".
We use it as a reference for the noise levels.
It can be downloded from their project page [https://bmild.github.io/kpn/index.html](https://bmild.github.io/kpn/index.html).

The direct link to the data is [https://drive.google.com/open?id=1UptBXV4f56wMDpS365ydhZkej6ABTFq1](https://drive.google.com/open?id=1UptBXV4f56wMDpS365ydhZkej6ABTFq1).

**Comment by liza-li** [comment]
@NaamaPearl @520jz Hi, I encountered an issue with accessing the link to download the file synthetic_5d_j2_16_noiselevels6_wide_438x202x320x8.npz. I’ve tried alternative links, but none seem to be working. Would you be able to share the file with me?

**Comment by xizero00** [comment]
> Hi,
> 
> This file is the test set in the paper "KPN: Burst Denoising with Kernel Prediction Networks". We use it as a reference for the noise levels. It can be downloded from their project page https://bmild.github.io/kpn/index.html.
> 
> The direct link to the data is https://drive.google.com/open?id=1UptBXV4f56wMDpS365ydhZkej6ABTFq1.

Hi,  the data link is not accessable.
Could you please grant the access authority?
Thanks.

**Comment by sumit171993** [comment]
Yes this link:  https://drive.google.com/open?id=1UptBXV4f56wMDpS365ydhZkej6ABTFq1 , is not working. Also I checked this : https://bmild.github.io/kpn/index.html , this link also is not working. Please do the needful asap.
