### ISSUE TITLE
Whether a dataset is available

### ISSUE THREAD

**Issue by 520jz** [NaamaPearl/nan#13]
Hello, thank you very much for your excellent work. Can you provide these datasets with noise? We need it badly
![image](https://github.com/user-attachments/assets/7cef7bd7-a541-4f87-8063-1d349ed6fa70)

**Comment by NaamaPearl** [comment]
Hi,

We created the dataset on-the-fly, in the [`NoisyDataset`](https://github.com/NaamaPearl/nan/blob/master/nan/dataloaders/basic_dataset.py#L142), then the noise can be added in the same way to all used datasets.

**Comment by 520jz** [comment]
> Hi,
> 
> We created the dataset on-the-fly, in the [`NoisyDataset`](https://github.com/NaamaPearl/nan/blob/master/nan/dataloaders/basic_dataset.py#L142), then the noise can be added in the same way to all used datasets.



> Hi,
> 
> We created the dataset on-the-fly, in the [`NoisyDataset`](https://github.com/NaamaPearl/nan/blob/master/nan/dataloaders/basic_dataset.py#L142), then the noise can be added in the same way to all used datasets.

**Comment by 520jz** [comment]
> Hi,
> 
> We created the dataset on-the-fly, in the [`NoisyDataset`](https://github.com/NaamaPearl/nan/blob/master/nan/dataloaders/basic_dataset.py#L142), then the noise can be added in the same way to all used datasets.

Okay, thank you very much

**Comment by 520jz** [comment]
> Hi,
> 
> We created the dataset on-the-fly, in the [`NoisyDataset`](https://github.com/NaamaPearl/nan/blob/master/nan/dataloaders/basic_dataset.py#L142), then the noise can be added in the same way to all used datasets.

Hello, would I like to confirm that the model only needs a clear dataset when it is trained? Is the corresponding noise only added during testing?

**Comment by 520jz** [comment]
> Hi,
> 
> We created the dataset on-the-fly, in the [`NoisyDataset`](https://github.com/NaamaPearl/nan/blob/master/nan/dataloaders/basic_dataset.py#L142), then the noise can be added in the same way to all used datasets.

Hello, would I like to confirm that the model only needs a clear dataset when it is trained? Is the corresponding noise only added during testing?


> Hi,
> 
> We created the dataset on-the-fly, in the [`NoisyDataset`](https://github.com/NaamaPearl/nan/blob/master/nan/dataloaders/basic_dataset.py#L142), then the noise can be added in the same way to all used datasets.

Hello, would I like to confirm that the model only needs a clear dataset when it is trained? Is the corresponding noise only added during testing?
![image](https://github.com/user-attachments/assets/df799608-47a9-47e6-95bc-0f18e780105b)
