### ISSUE TITLE
More detailed description for your data requirements.

### ISSUE THREAD

**Issue by ZhangXiaoXuan2019** [NaamaPearl/nan#3]
Hi! First of all, thanks for your impressive work on denoising with NeRF-like methods.
When I try to run the `train.py` by default configurations, I detect that a noise data file called `synthetic_5d_j2_16_noiselevels6_wide_438x202x320x8.npz` should be download before training. 
Please notice the followers about it, for better results re-producting with your code.

**Comment by NaamaPearl** [comment]
Hi, 

Thanks for your comment, I missed this file in the documentation. 

The file is used to reproduce the noise levels in evaluation and can be found in the [KPN website](https://bmild.github.io/kpn/index.html).
Here is a direct link for downloading: [`Synthetic test set (as numpy data)`](https://drive.google.com/open?id=1UptBXV4f56wMDpS365ydhZkej6ABTFq1).
