### ISSUE TITLE
Testing real burst 

### ISSUE THREAD

**Issue by Vinayak-VG** [NaamaPearl/nan#6]
Hi, I saw the other issue where you tried to tell the procedure you used to extract the noisy image using the rawpy library. I tried it but I am not able to match the noisy data similar to yours. There seems to be a colour mismatch between my image and yours. Can you send a snippet of the code you used to extract the dng images using the rawpy.

**Comment by NaamaPearl** [comment]
Hi,

The color differences are from the post-processing stage of the low-light images.
As the focus of the work was denoising and not the general appearance of the final image, this was done as a global normalization step manually for visualization purposes.

Unfortunately, I don't have the specific parameters that we used for each scene.
