### ISSUE TITLE
Quantitative Results on the LLFF-Noise Data

### ISSUE THREAD

**Issue by Vinayak-VG** [NaamaPearl/nan#7]
In the paper, I see that you haven't quantitatively reported the results properly. I see a graph, but that doesn't give us the exact numbers. Can you please give us the exact quantitative numbers for each of the gain you simulated.

**Comment by NaamaPearl** [comment]
Hi,

Attached are the quantitive values for the burst denoising in Figure 9.

[CVPR2022_NAN_Fig9metrics.txt](https://github.com/NaamaPearl/nan/files/13939283/CVPR2022_NAN_Fig9metrics.txt)
