### ISSUE TITLE
Link temporarily disabled about the real noisy data

### ISSUE THREAD

**Issue by zkaiWu** [NaamaPearl/nan#8]
![image](https://github.com/NaamaPearl/nan/assets/53325998/4e3d69c2-912e-4bc1-b875-2f7f6948af8c)

The links for real noisy data and LLFF-N data are disabled.

**Comment by NaamaPearl** [comment]
Thanks for pointing this out.

I have updated the links, let me know if there is still a problem.

**Comment by zkaiWu** [comment]
It works, thanks.

But why isn't there any file about camera parameters in the real-world dataset.
